FROM python:3.10-slim

WORKDIR /app
COPY requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r requirements.txt
COPY app.py /app/app.py
COPY static /app/static
COPY app /app/app
COPY common /app/common
COPY text_service /app/text_service
COPY audio_service /app/audio_service
COPY docs /app/docs
EXPOSE 8000
CMD ["python", "app.py", "8000"]
